version: "3"

services:

  db:
    
    build:
      context: .
      dockerfile: db.dockerfile

    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data
      
    ports:
      - "6789:5432"

    # postgres password should be defined in .env
    env_file: .env

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USERNAME: fusionauth
      DATABASE_PASSWORD: ${FA_DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FA_FUSIONAUTH_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_TYPE: database

    ports:
      - 9011:9011

    volumes:
      - fa_config:/usr/local/fusionauth/config

volumes:
  dbdata:
  fa_config: